project:
  type: website
  output-dir: _site

resources:
  - src/**
  - index.js
  - datasets/**
  - static-charts/**

website:
  title: "Interactive Globe Story"
  navbar:
    left:
      - text: Globe
        href: index.qmd

format:
  html:
    theme: darkly
    page-layout: full
    lightbox: true
    theme-toggle: false
    fontfamily: "Oswald, serif"
    toc: true
    embed-resources: true

